# Gene Expression Analysis under Oxidative Stress

## Introduction
This project analyzes how normal pancreatic cells (hTERT-HPNE) and tumor cells 
(PANC-1) respond to oxidative stress induced by H2O2, through differential gene 
expression analysis using RNA-seq data from study GSE196284 (Liu et al., Antioxidants, 2022).

## Dataset
- **Source:** Gene Expression Omnibus (GEO) — GSE196284
- **Organism:** Homo sapiens
- **Data type:** RNA-seq raw counts
- **Conditions:** Normal cells (HPNE) vs tumor cells (PANC-1), with and without H2O2 treatment

## Data Dictionary
| Sample | Cell type | Condition |
|--------|-----------|-----------|
| GSM5866903 | hTERT-HPNE (normal) | Control |
| GSM5866904 | hTERT-HPNE (normal) | H2O2 (oxidative stress) |
| GSM5866905 | PANC-1 (tumor) | Control |
| GSM5866906 | PANC-1 (tumor) | H2O2 (oxidative stress) |

## Objectives
1. Explore and understand the structure and quality of gene expression data
2. Identify differentially expressed genes between conditions
3. Build a classification model to predict cell type and condition
4. Deploy results as a REST API in the cloud

In [2]:
#Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
# Visualization settings

sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

## 1. Data loading

In [4]:
# Dataset loading
df_counts_raw = pd.read_csv(
    '../data/GSE196284_raw_counts_GRCh38.p13_NCBI.tsv.gz',
    sep='\t',
    compression='gzip'
)

print(f"Dataset cargado: {df_counts_raw.shape[0]} genes x {df_counts_raw.shape[1]} columnas")
df_counts_raw.head()

Dataset cargado: 39376 genes x 5 columnas

      GeneID  GSM5866903  GSM5866904  GSM5866905  GSM5866906
0  100287102           4           7          21          14
1     653635         241         305         611         652
2  102466751           6          17          26          39
3  107985730           0           0           0           0
4  100302278           0           0           0           0

## 2. Initial Exploration

In [6]:
df_counts_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 39376 entries, 0 to 39375
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GeneID      39376 non-null  int64
 1   GSM5866903  39376 non-null  int64
 2   GSM5866904  39376 non-null  int64
 3   GSM5866905  39376 non-null  int64
 4   GSM5866906  39376 non-null  int64
dtypes: int64(5)
memory usage: 1.5 MB

In [7]:
df_counts_raw.describe()

             GeneID    GSM5866903    GSM5866904     GSM5866905     GSM5866906
count  3.937600e+04  3.937600e+04  3.937600e+04   39376.000000   39376.000000
mean   4.441428e+07  8.553432e+02  8.247941e+02    1334.672135    1146.625533
std    5.159676e+07  1.358934e+04  1.721197e+04    8416.512797    6903.697262
min    1.000000e+00  0.000000e+00  0.000000e+00       0.000000       0.000000
25%    2.878250e+04  0.000000e+00  0.000000e+00       0.000000       0.000000
50%    3.764545e+05  4.000000e+00  6.000000e+00       7.000000       6.000000
75%    1.053697e+08  2.930000e+02  2.740000e+02     461.250000     415.500000
max    1.156947e+08  1.701589e+06  2.331029e+06  751851.000000  611011.000000

In [9]:
# Rename columns with meaningful names
df_counts_raw.rename(columns={
    'GSM5866903': 'HPNE_Control',
    'GSM5866904': 'HPNE_H2O2',
    'GSM5866905': 'PANC1_Control',
    'GSM5866906': 'PANC1_H2O2'
}, inplace=True)

df_counts_raw.head()

      GeneID  HPNE_Control  HPNE_H2O2  PANC1_Control  PANC1_H2O2
0  100287102             4          7             21          14
1     653635           241        305            611         652
2  102466751             6         17             26          39
3  107985730             0          0              0           0
4  100302278             0          0              0           0